### ISSUE TITLE
what will do next step?

### ISSUE THREAD

**Issue by shellRaining** [shellRaining/hlchunk.nvim#40]
Add animation effects to the chunk~
change vim.fn function to utils function, because such as vim.fn.line() is so confused for its 1-base index
Improve multi-person cooperation process
Improve documentation (including extreme cases where indent cannot be rendered, and the functionality of text objects in chunks).

However, due to exams in the next two weeks, updates will be slow.😄

**Comment by linrongbin16** [comment]
small feature request:

use syntax highlight color code instead of harding code: `"#806d9c"`.

For example I'm configure this plugin with:

```lua
---@return string?
local function hlcode(name)
    local hlnr = vim.fn.hlID(name)
    if type(hlnr) ~= "number" or hlnr <= 0 then
        return nil
    end
    local synnr = vim.fn.synIDtrans(hlnr)
    if type(synnr) ~= "number" or synnr <= 0 then
        return nil
    end
    local guicode = vim.fn.synIDattr(synnr, "fg", "gui")
    if type(guicode) == "string" and string.len(guicode) > 0 then
        return guicode
    end
    return vim.fn.synIDattr(synnr, "fg", "cterm")
end

local HL = "#806d9c"
local ERRHL = "#c21f30"

do
    local line_nr = hlcode("Constant")
    if line_nr then
        HL = line_nr
    end
    local err_msg = hlcode("ErrorMsg")
    if err_msg then
        ERRHL = err_msg
    else
        err_msg = hlcode("DiagnosticError")
        if err_msg then
            ERRHL = err_msg
        end
    end
end

require("hlchunk").setup({
    chunk = {
        notify = false,
        style = {
            { fg = HL },
            { fg = ERRHL },
        },
    },
    line_num = {
        enable = true,
        use_treesitter = false,
        style = HL,
    },
    blank = {
        enable = false,
    },
})
```

It looks different when I use different colorscheme:

https://github.com/catppuccin/nvim:

https://github.com/shellRaining/hlchunk.nvim/assets/6496887/22485890-963d-4612-9830-5c3d5f4d80e8


https://github.com/sainnhe/edge

https://github.com/shellRaining/hlchunk.nvim/assets/6496887/c66d7928-eeab-44ac-b9fc-6bcebb79b02b

https://github.com/sainnhe/gruvbox-material:

https://github.com/shellRaining/hlchunk.nvim/assets/6496887/9fb501b0-7869-4602-be1b-f1dfca68b149

(and we could select a more suitable syntax color instead of `Constant`)

**Comment by linrongbin16** [comment]
Please add a delay time for showing chunk, when cursor move up/down fast, it's not necessary to show chunk for every movement.

**Comment by shellRaining** [comment]
> Please add a delay time for showing chunk, when cursor move up/down fast, it's not necessary to show chunk for every movement.

OK, try to add a Debounce this weekend
