### ISSUE TITLE
Notification "You have disable this plugin" appears when using default configuration from readme

### ISSUE THREAD

**Issue by miversen33** [shellRaining/hlchunk.nvim#9]
**Describe the bug**
When using the default configuration provided [in the readme](https://github.com/shellRaining/hlchunk.nvim#lazy)
```lua
{ "shellRaining/hlchunk.nvim", event = { "UIEnter" }, },
```
A notification is displayed on Vim start that says 

> you have disable this plugin

![image](https://user-images.githubusercontent.com/2640668/230942811-082a57da-572b-4ffa-93c2-d93b41dbfee7.png)

**To Reproduce**
Install hlchunk.nvim, use the configuration provided in the readme, open a file with neovimvim

I am using neovim stable
```
NVIM v0.9.0
Build type: Release
LuaJIT 2.1.0-beta3
```

**Expected behavior**
I would expect the provided configuration to work "out of the box". If we need to manually enable specific features to make it work, that should be notated in the readme. It appears that the only way to make this notification not appear is to enable _all_ features of the plugin. Which is fine, but that should be notated.

Additionally, the readme states [the default configuration is supposed to have all parts of hlchunk enabled](https://github.com/shellRaining/hlchunk.nvim#setup)

Lastly, disabling an optional piece of the plugin should not display a message on vim startup.

**Comment by shellRaining** [comment]
yes, this bug was introduced in commit https://github.com/shellRaining/hlchunk.nvim/commit/9cff52ad9fa48bf8676fbfcc1e02ad6f436ac9c3, in this commit i change the return type of `get_chunk_range` function from `table<int, int>` to `table<int, int> | nil`, the purpose is to check whether the function successfully returns a valid range. I checked nil in `hl_chunk` but forget `hl_line_num` also use this function, which introduce this bug.

thanks a lot for finding and fixing this bug, i will merge it later. To prevent this kind of problem, i will strengthen the strictness of `luacheck` and add more type annotation. There will be many changes in this repository in the coming days. I will improve it as soon as possible and provide a stable version.

And also thank you very much for taking interest in this plugin. 😊 this is the first neovim plugin I have written, so there may be many shortcomings, hope you can give me more guidance and feedback.
